# Generated by Django 4.2.2 on 2023-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(blank=True, max_length=7, verbose_name='Precio')),
                ('descripcion', models.CharField(blank=True, max_length=50, verbose_name='Descripcion')),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Caregoria')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
            ],
        ),
    ]
