# Generated by Django 4.2.2 on 2023-06-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Productos',
        ),
    ]
